name: 'Soma'
author: 'yraeel'
description: 'Soma'
inputs:
  a:
    required: true
  b:
    required: false
runs:
  using: 'composite'

  steps:

    - name: Checkout repository content
        uses: actions/chechout@v2

    
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: run Soma
      shell: bash
      run: python soma.py -d=${{ inputs.a }} -l=${{ inputs.b }}
