name: 'Soma'
author: 'yraeel'
description: 'Soma'
inputs:
  a:
    required: true
  b:
    required: true
runs:
  using: 'composite'

  steps:

    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: run Soma
      shell: bash
      run: python soma.py -a=${{ inputs.a }} -b=${{ inputs.b }}
